Add controllers
SidyakinV/java-shareit pull request #1
Opened 2024-04-26 07:17 UTC by SidyakinV

2024-04-27 17:18 UTC, TomattmanYandex requested changes
Привет, работа хорошая, есть пара комментов на улучшение

2024-04-27 17:18 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapping.java
> +public class ItemMapping {
я бы порекомендовал называть ItemMapper так как то более принято

2024-04-27 17:18 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        checkUserExists(item.getOwnerId());
тут есть рекомендация, она будет в комменте на этом методе

2024-04-27 17:18 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private void checkUserExists(Long userId) {
рекомендации следующие
1) сделать возвращаемый тип User
2) переименовать в getUserById

а лучше, так как ты на уровне сервиса работаешь с классами моделями вообще заинжектить сюда юзер сервис, и использовать метод userService.getById(id)

теперь объяснение почему
очень часто, если мы проверяем наличие существования, то потом надо использовать этот обьект, и так будет сразу два в одном, нужно значение, результат выполнения записали в переменную и используем, не нужно
просто игнорим результат выполнения, а если выполнилось успешно, то значит все валидно

2024-04-27 17:18 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private void checkItemExists(Item item, Long itemId) {
тут то же что и выше, это может быть логикой основного метода

2024-04-27 17:18 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/repository/InMemUserRepository.java
> +    public User getUser(Long userId) {
вот ты можешь этот метод использовать в itemService чтобы не делать дополнительные проверки на существование пользователя
и второе, зачем тебе метод, который только и делает что вызывает другой метод с теми же параметрами? может тебе не нужен второй метод

2024-04-28 04:25 UTC, SidyakinV commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private void checkUserExists(Long userId) {
Мне кажется, не очень хорошая идея подключать один сервис к другому, т.к. если вдруг потом потребуется подключить второй сервис к первому, то возникнет циклическая зависимость. Поэтому я вообще стараюсь избегать таких ситуаций.

По повод самого метода. Его основная задача - выбросить исключение в случае, если указанный пользователь отсутствует, потому он и называется check... А вот если бы нам нужно было бы использовать атрибуты юзера, то да, логичнее было бы назвать метод get... и возвращать уже сам объект. 
Кроме того, если сделать возвращаемый тип и потом его не использовать, умная Idea сразу начинает предупреждать об этом.

2024-04-28 04:55 UTC, SidyakinV commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private void checkItemExists(Item item, Long itemId) {
Этот метод вообще никак не взаимодействует с уровнем данных. Его единственная задача - выбросить исключение в случае, если входной параметр null. И вызывается он уже после того, как произошли какие-то манипуляции с данными.

2024-04-28 05:19 UTC, SidyakinV commented on src/main/java/ru/practicum/shareit/user/repository/InMemUserRepository.java
> +    public User getUser(Long userId) {
Сейчас именно так и сделано - в ItemService в checkUserExists дергается метод userRepository.getUser(userId).
Зачем нужен второй метод? Для тестов Postman'а, для выброса исключения в случае, если юзер не найден.
А так то да, можно было бы просто сделать проверку if (getUser != null) { ... }

2024-04-29 09:04 UTC, TomattmanYandex approved these changes
Принято

2024-04-29 09:04 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private void checkUserExists(Long userId) {
по первому согласен полностью
по второму это была рекомендация, ибо чаще всего именно так и приходится делать, но в конкретно этом случае все норм

2024-04-29 09:04 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private void checkItemExists(Item item, Long itemId) {
тут только вопрос универсальности, можно просто использовать один метод getById в котором будет эта проверка, потому что скорее всего этот метод ты будешь использовать только в нем

2024-05-05 15:39 UTC, merged