Add bookings
SidyakinV/java-shareit pull request #2
Opened 2024-05-14 08:14 UTC by SidyakinV

2024-05-15 12:32 UTC, TomattmanYandex requested changes
Привет, я оставил несколько комментов, то что пометил повторяется много где, я везде не помечал, а так в целом хорошая работа

2024-05-15 12:32 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/dto/ResponseBookingDto.java
> +public class ResponseBookingDto {
Я бы посоветовал переименовать в BookingResponseDto

2024-05-15 12:32 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    private Long itemId;
зачем тут и itemId и item, следует оставить только item

2024-05-15 12:32 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    private Long userId;
тут тоже вместо id лучше всего юзера хранить

2024-05-15 12:32 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/model/BookingState.java
> +    public static BookingState stringToBookingState(String value) {
немного не понятно зачем этот метод
но ладно

2024-05-15 12:32 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/repository/JpaBookingRepository.java
> +            "  AND (:state is null OR b.state = :state) " +
в модели помечено но state не может быть null тогда зачем первая проврека

2024-05-15 12:32 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/repository/JpaBookingRepository.java
> +    List<Booking> getUserBookings(long userId, BookingState state);
у jpa есть способность генирировать все автоматически по имени метода
можно сделать метод c именем
findByUserIdAndState
и он будет делать все то же самое

2024-05-15 12:32 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/repository/JpaBookingRepository.java
> +    List<Booking> getUserBookings(long userId, BookingState state);
единственная загвоздка может быть в зависимости от FetchType
если он ленивый, то айтем будет получен только при обращении отдельным запросом если нет, то через джойн

2024-05-15 12:32 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (booking.getEnd().isBefore(booking.getStart()) || booking.getEnd().isBefore(LocalDateTime.now())) {
я бы вынес все проверки времени в отдельный метод, кажется это улучшит чтение

2024-05-15 12:32 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    private void checkUserExists(Long userId) {
тут можно было бы сделать возвращаемое значение User и назвать getUserById было бы чуть универсальнее

2024-05-15 12:32 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +    private Long userId;
про это я уже писал в другой модели

2024-05-15 12:32 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +    private Long itemId;
и про это

2024-05-16 05:12 UTC, SidyakinV commented on src/main/java/ru/practicum/shareit/booking/model/BookingState.java
> +    public static BookingState stringToBookingState(String value) {
Чтобы сгенерить эксепшн в том виде, при котором проходят тесты.

2024-05-16 05:21 UTC, SidyakinV commented on src/main/java/ru/practicum/shareit/booking/repository/JpaBookingRepository.java
> +            "  AND (:state is null OR b.state = :state) " +
В запрос данный параметр передается вручную, а не из модели. 
Если передали null, то вернутся все записи, если же указали конкретный тип, то вернутся записи только с этим типом.
Делать разными запросами, имхо, не очень хорошая идея. Во-первых, если потребуется внести изменения, то их нужно будет вносить во все запросы. А во-вторых, если этих критериев несколько, не городить же под каждый из них свой запрос, тем более, что из критериев может быть комбинация.

2024-05-16 05:31 UTC, SidyakinV commented on src/main/java/ru/practicum/shareit/booking/repository/JpaBookingRepository.java
> +    List<Booking> getUserBookings(long userId, BookingState state);
Да, можно было и по имени. Но в данном случае сделал так по двум причинам. Первое - возможность передавать null в качестве параметра. И второе - чтобы принудительно указать, что все связанные данные должны подтягиваться сразу, а не при обращении к ним (т.к. формируется список, а нам лишние N+1 запросы не нужны).

2024-05-16 09:06 UTC, SidyakinV commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    private Long itemId;
Не знаю, есть какой-то общепринятый стандарт на то, какой объект передавать из контроллера в сервис - сам объект или его dto.
Я исходил из того, что передавать лучше сам объект. Но для того, чтобы его заполнить всеми связанными объектами, надо тащить репозитории либо на уровень контроллера, либо на уровень маппера. Ну либо сам маппер на уровень сервиса помещать. В общем, все решения показались как-то не очень. Потому то и ввел дополнительные поля. Хотя вот сейчас свежим взглядом посмотрел - тоже такое себе решение.
Переделал, теперь в сервис передается dto, и там уже производятся все необходимые действия. Соответственно, и лишние поля убрались.

2024-05-17 07:04 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    private Long itemId;
на этот момент могу сказать, что это вопрос интересные, и его стоит пообдумывать, и я обычно тоже передаю Dto  с контроллера в сервис, но при проверке работ, натыкался работы, в которых на уровне контроллера был маппер, и преобразования были именно там
А что касается моделей, то можно же передать обьект у которого будет другой обьект и во вложенном будет только поле id заполнено, и этого достаточно, ну или просто id вложенного объекта, другим параметром

2024-05-17 07:10 UTC, TomattmanYandex approved these changes
Принято

2024-05-17 07:10 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @ManyToOne(fetch = FetchType.LAZY)
скорее всего букинг мы будем всегда запрашивать с предметом и пользователем который его сделал, поэтому можно FetchType.EAGER использовать

2024-05-17 07:10 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +    @ManyToOne(fetch = FetchType.EAGER)
а вот тут как раз скорее всего у нас уже будет айтем к которому мы запрашиваем комментарии и возможно лучше бы подошло FetchType.LAZY

2024-05-17 07:27 UTC, merged