Add item requests
SidyakinV/java-shareit pull request #3
Opened 2024-05-22 10:13 UTC by SidyakinV

2024-05-29 08:19 UTC, TomattmanYandex requested changes
Привет, хорошая работа, есть моменты на улучшение

2024-05-29 08:19 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/dto/BookingResponseDto.java
> +    private String start;
Почему тут строка? это де дата
Посмотри в сторону всяких адаптеров, чтобы выводить в нужном формате, если проблема в этом

2024-05-29 08:19 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        if (from != null) {
многовато логики для контролера, а еще код дублируется
я бы предложил передавать на уровень сервиса 3 параметра userId, from, size и там это все подсчитывать, и сделать для этого отдельны метод

а так как пагинация во множестве мест, то может стоит сделать отдельный класс со статическим методом, который будут использовать все сервисы

2024-05-29 08:19 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingJsonTests.java
> +    @Test void testBookingResponseDto() throws JsonProcessingException {
форматирование поехало, и выглядит так себе

2024-05-29 08:19 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingServiceTests.java
> +    @Test
обычно в реализации интеграционных тестах я в сам тест инжекчу сервис или контроллер, вызываю действие из него, а потом через также заинжектанный репозиторий делаю запрос за данными
это так же проверяет что все данные дошли до нужного уровня и потом можно провести проверку на правильность данных, но за то реализовывать гораздо легче, ибо не надо создавать дополнительные запросы

2024-05-30 05:58 UTC, SidyakinV commented on src/main/java/ru/practicum/shareit/booking/dto/BookingResponseDto.java
> +    private String start;
Здесь два аспекта. Первый - это DTO, которое работает с JSON, который, по сути, есть текст. Второй - из-за того-же JSON, точнее, из-за его тестов, возникла какая-то несовместимость, в связи с чем я и переделал дату на строку.
Наверное, можно было бы как-то покрасивее этот момент обыграть, но предстоящий жесткий дедлайн как-то не особо располагает к изысканиям.

2024-05-30 06:02 UTC, SidyakinV commented on src/test/java/ru/practicum/shareit/booking/BookingJsonTests.java
> +    @Test void testBookingResponseDto() throws JsonProcessingException {
Не совсем понял, про что это. Форматирование Идея сделала. Подправил немного ручками.

2024-05-30 06:10 UTC, SidyakinV commented on src/test/java/ru/practicum/shareit/booking/BookingServiceTests.java
> +    @Test
Мне тоже такой вариант кажется более логичным. Но проблема в том, что на курсе вообще ничего не говорится про то, какие варианты решения задачи есть, и какие из них наиболее предпочтительнее. Типа как сделали так и сделали :)
Ну а посему, т.к. мы тестируем слой сервиса, то я и сделал реализацию только на этом слое, без привлечения репозитариев.

2024-05-30 07:03 UTC, SidyakinV commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        if (from != null) {
Согласен, некрасиво получилось. Переделал.

2024-05-30 08:20 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/dto/BookingResponseDto.java
> +    private String start;
y gson есть разделение по типам? но да, у дат они не отличаются от строк
но вообще использование подходящих типов очень облегчает работу, потому что чаще всего спринг сам умеет приводить к нужным типам объектов и не надо как раз таки ничего преобразовывать

2024-05-30 08:22 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingJsonTests.java
> +    @Test void testBookingResponseDto() throws JsonProcessingException {
@Test в одной строчке с самим методом, переделать бы

2024-05-30 08:22 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingServiceTests.java
> +    @Test
а это было просто наблюдение как можно сделать легче
потому что стилей написания тестов есть очень много, и в разных командах они могут быть совершенно разные, и я при проверках продвигаю свой вариант, кто то другой

2024-05-30 08:22 UTC, TomattmanYandex approved these changes
Принято

2024-05-30 16:26 UTC, merged